name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - name: 📂 setup
        uses: actions/checkout@v2
        # for jekyll-last-modified-at, may be very slow for large repositories!
        # with:
          # fetch-depth: '0'

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          # format_output: true
          ### Uses prettier https://prettier.io to format jekyll output HTML.
          #
          # prettier_opts: '{ "useTabs": true }'
          ### Sets prettier options (in JSON) to format output HTML. For example, output tabs over spaces.
          ### Possible options are outlined in https://prettier.io/docs/en/options.html
          # jekyll_src: sample_site
          ### If the jekyll website source is not in root, specify the directory. (in this case, sample_site)
          ### By default, this is not required as the action searches for a _config.yml automatically.

      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.JEKYLL_PAT }}
          publish_dir: ./_site
